version: '3.9'

services:
  server:
    build:
      context: ../..
      dockerfile: packages/twenty-server/Dockerfile.dev
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      REDIS_URL: redis://redis:6379
    command: yarn workspace twenty-server start:dev
    depends_on:
      - db
      - redis

  front:
    build:
      context: ../..
      dockerfile: packages/twenty-front/Dockerfile.dev
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    command: yarn workspace twenty-front dev
    depends_on:
      - server

  db:
    image: postgres:16
    container_name: twenty-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: twenty-redis
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    ports:
      - "6379:6379"

volumes:
  db-data:
