version: '3.9'

services:
  server:
    volumes:
      - ../..:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"

  front:
    volumes:
      - ../..:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
